'use strict';

// Single source of truth for every field a mauto observability event can
// carry, and — critically — whether that field may ever cross a network.
//
// This mirrors src/device/action-catalog.js and src/result/capability-catalog.js:
// one entry per item, consumed by a lint guard (tests/lint/telemetry-redaction.test.js)
// so a field that gains a network path fails the build instead of silently
// shipping a user's unreleased app id to a third party.
//
//   sends: true  — may appear in slice 5's telemetry payload. Only enumerated
//                  values, counts, versions and durations qualify.
//   sends: false — local logs only. telemetryPayload() cannot serialize it.
//
// The allowlist direction is deliberate: a field nobody has classified is
// silently DROPPED from telemetry rather than silently sent.

const pkg = require('../../package.json');

const EVENT_VERSION = 1;

// Ascending severity. Index order is the comparison order.
const LEVELS = ['debug', 'info', 'warn', 'error'];

// The closed set of mechanisms that can make a `sends: true` classification
// true. This is the enforceable half of that classification; `why` is the
// human-readable half. A `why` string can be reworded to satisfy a reviewer
// (or a regex) without the underlying value ever becoming safe — `basis`
// cannot, because tests/lint/telemetry-redaction.test.js checks it against
// this exact list, the same way tests/lint/action-coverage.test.js checks
// src/device/action-catalog.js's `resolution` against `RESOLUTIONS`.
//
//   'computed'   — this code derives the value (a timestamp, a duration, a
//                  monotonic counter, a Number.isFinite-checked count, a
//                  boolean outcome, a status code read from our own endpoint).
//                  Never a value copied verbatim from caller input.
//   'closed-set' — the value is drawn from, or checked against, a fixed
//                  vocabulary we define or a runtime-level enum (os, errno).
//   'csprng'     — a zero-arity CSPRNG generator, derived from nothing.
//   'constant'   — a fixed fact about the build/runtime (a version string),
//                  never a caller-supplied or per-invocation value.
const SEND_BASES = ['computed', 'closed-set', 'csprng', 'constant'];

const EVENT_FIELDS = {
  // --- ambient, stamped by makeEvent -------------------------------------
  ts: { sends: true, basis: 'computed', why: 'ISO timestamp; carries no user content' },
  v: { sends: true, basis: 'constant', why: 'event schema version' },
  mauto_version: { sends: true, basis: 'constant', why: 'our own package version' },
  node: { sends: true, basis: 'constant', why: 'node runtime version' },
  os: { sends: true, basis: 'closed-set', why: 'process.platform; one of a fixed set' },

  // --- classification ----------------------------------------------------
  level: { sends: true, basis: 'closed-set', why: 'enumerated: debug|info|warn|error' },
  src: { sends: true, basis: 'closed-set', why: 'enumerated: cli|daemon' },
  event: { sends: true, basis: 'closed-set', why: 'enumerated event name' },

  // --- outcome -----------------------------------------------------------
  // The justification is only true if the value is enforced to be one: cli.js
  // takes it from commander's resolved command, never from argv, so an
  // unparseable invocation records no verb rather than a user-supplied token.
  verb: { sends: true, basis: 'closed-set', why: 'the mauto verb name; a fixed vocabulary we ship' },
  ok: { sends: true, basis: 'computed', why: 'boolean outcome' },
  error_kind: { sends: true, basis: 'closed-set', why: 'enumerated envelope taxonomy (device|timeout|...)' },
  exit_code: { sends: true, basis: 'closed-set', why: 'enumerated exit code' },
  dur_ms: { sends: true, basis: 'computed', why: 'duration; carries no user content' },

  // --- daemon ------------------------------------------------------------
  // Random per-daemon-lifetime id, generated by session-handle.newSessionId()
  // from crypto.randomBytes and derived from NOTHING — not the project root,
  // not the device, not the pid. Deliberately NOT persisted across restarts: a
  // stable id would be a machine fingerprint, whereas this one changes exactly
  // when the daemon does, which is the fact it exists to report. Enforced by
  // tests/unit/device/session-handle.test.js.
  session_id: { sends: true, basis: 'csprng', why: 'random id scoped to one daemon lifetime; no user-derived content' },
  // As with `verb`, the justification holds only because the value is enforced
  // to be one: src/device/device-call.js records this field ONLY when
  // isKnownTool() accepts it (src/device/mobile-mcp-tools.js), because it
  // arrives inside a socket frame and the socket is reachable by anything on
  // the machine. It is checked there — in the one wrapper every daemon call
  // goes through — rather than at the daemon's frame router, so a second call
  // site cannot appear that forgets to check.
  tool: { sends: true, basis: 'closed-set', why: 'mobile-mcp primitive name, checked against the pinned tool set' },
  // Monotonic integer minted by startDaemon, one per device call, scoped to one
  // daemon lifetime. It is what makes call.start and call.end PAIRABLE: every
  // call in a lifetime shares session_id and the daemon multiplexes, so a
  // start-without-end — the only trace a call that never returned can leave —
  // is undecidable without a per-call identity.
  //
  // The daemon already has a correlation id in the socket frame's `req.id`, and
  // deliberately does not use it: that value is client-chosen and the socket is
  // reachable by any process on the machine, so recording it would put caller
  // text on a sends:true field — the same concern that produced
  // src/device/mobile-mcp-tools.js. A daemon-minted counter needs no redaction
  // argument at all, on exactly the grounds dur_ms is cleared.
  call_id: { sends: true, basis: 'computed', why: 'daemon-minted counter scoped to one session; never the client-supplied frame id' },
  stop_reason: { sends: true, basis: 'closed-set', why: 'enumerated: idle|signal|shutdown|crash|explicit' },
  error_code: { sends: true, basis: 'closed-set', why: "Node/libuv errno string (EADDRINUSE|EACCES|…) plus our own ELOCKED" },

  // --- crash (slice 4) ---------------------------------------------------
  // The ONLY new field slice 4 mints. As with `verb`, `tool` and `session_id`,
  // the sends:true justification is only true if the value is enforced to be
  // one: every record site coerces with Number.isFinite before recording, so a
  // malformed engine payload records no field rather than an arbitrary value.
  //
  // Deliberately no crash_process / crash_excerpt / crash_path fields: a
  // crashed process name IS an app id, a stack excerpt IS free text and a
  // report location IS a filesystem path. Those three entries already carry the
  // right classification, and a near-copy would be a second decision to keep in
  // sync with the first.
  crash_count: { sends: true, basis: 'computed', why: 'integer count of crash reports observed; carries no user content' },

  // --- telemetry transport (slice 5) --------------------------------------
  // Zero-arity CSPRNG token, generated per EVENT at spool time by
  // src/observe/spool.js newMessageId() and derived from NOTHING — not the
  // project root, not the pid, not the clock. It is sent as the PostHog
  // event's `uuid` so a re-sent batch (delivery is at-least-once; see
  // src/observe/flush.js) deduplicates at ingestion. Per-event and never
  // reused, so it cannot correlate two events, let alone two machines — the
  // opposite of the stable install id this design deliberately does not have.
  // It is sends:true on EXACTLY the grounds session_id is.
  msg_id: { sends: true, basis: 'csprng', why: 'zero-arity CSPRNG per-event delivery id; carries no user content' },
  // Integer this code computes (batch size), never a caller-supplied value.
  count: { sends: true, basis: 'computed', why: 'integer count (batch size); carries no user content' },
  // Integer our own telemetry endpoint returns; never a caller-supplied value.
  http_status: { sends: true, basis: 'computed', why: 'integer HTTP status from our own telemetry endpoint' },

  // --- local only: every one of these can carry user content -------------
  run_id: { sends: false, why: 'agent-chosen; routinely names an unreleased feature' },
  scenario_id: { sends: false, why: "names the user's feature under test" },
  app_id: { sends: false, why: "an unreleased product's package name" },
  device_id: { sends: false, why: 'hardware identifier / serial' },
  device_model: { sends: false, why: 'narrows a device to an individual tester' },
  project_name: { sends: false, why: "the user's project name" },
  pid: { sends: false, why: 'process id; no aggregate value, and a weak host correlator with ts' },
  message: { sends: false, why: 'free text; may embed labels, paths, typed input' },
  hint: { sends: false, why: 'free text; may embed filesystem paths' },
  path: { sends: false, why: 'filesystem path; leaks usernames and project layout' },
};

// Names that must ALWAYS be sends:false. Kept separate from EVENT_FIELDS so
// the guard tests a stated intention against the catalog rather than reading
// the catalog and agreeing with itself.
const NEVER_SENDS = [
  'run_id',
  'scenario_id',
  'app_id',
  'device_id',
  'device_model',
  'project_name',
  'pid',
  'message',
  'hint',
  'path',
];

// Build an event from caller fields. Unknown keys are dropped (not an error:
// a caller that invents a field must not be able to smuggle it into a log),
// and undefined values are omitted so events stay sparse rather than
// null-padded.
// The ambient fields are classified sends:true on the grounds that makeEvent
// computes them (basis computed/constant/closed-set). That is only true if a
// caller cannot override them, so the caller loop below skips them.
const AMBIENT_FIELDS = new Set(['ts', 'v', 'mauto_version', 'node', 'os']);

function makeEvent(fields = {}) {
  const out = {
    ts: new Date().toISOString(),
    v: EVENT_VERSION,
    mauto_version: pkg.version,
    node: process.version,
    os: process.platform,
  };
  for (const [k, val] of Object.entries(fields)) {
    if (AMBIENT_FIELDS.has(k)) continue;
    if (!Object.prototype.hasOwnProperty.call(EVENT_FIELDS, k)) continue;
    if (val === undefined) continue;
    out[k] = val;
  }
  return out;
}

// The ONLY function permitted to build a network payload. Allowlist by
// construction: it iterates the catalog, never the event.
function telemetryPayload(event = {}) {
  const out = {};
  for (const [name, def] of Object.entries(EVENT_FIELDS)) {
    if (!def.sends) continue;
    if (!Object.prototype.hasOwnProperty.call(event, name)) continue;
    if (event[name] === undefined) continue;
    out[name] = event[name];
  }
  return out;
}

module.exports = { EVENT_VERSION, LEVELS, EVENT_FIELDS, NEVER_SENDS, SEND_BASES, makeEvent, telemetryPayload };
